### PR TITLE
Update fileTypes.json

### PR DESCRIPTION
**Pull request by anujdeshpande**
Change-type: minor
Signed-off-by: Anuj Deshpande <anuj@balena.io>

### CODE REVIEW

**Comment by anujdeshpande** [comment]
@balena-ci I self-certify!

**Review by ghost — APPROVED** [review]

**Comment by nazrhom** [comment]
@balena-ci retest

**Comment by rcooke-warwick** [comment]
@anujdeshpande @nazrhom, I'm wondering if we actually want to have a filetypes.json tbh, or just take every file from the outputs folder. Having the filetypes.json ensures that the lab only receives formats it can use, but it can just get those anyway. Moving forward, I image that maybe things like a BOM etc might also get included in the release, which means that we'll have to add even more file types to it

**Comment by anujdeshpande** [comment]
@rcooke-warwick I kind of like the idea of having file extensions because it makes it possible to have some check on what the user is sending the manufacturing lab. We wouldn't want to overshare with some labs.
Maybe there's a cleaner way to do this - and also maybe better logs so that the user knows what they did wrong.

**Pull request merged**
